name: Tests

on: [push]

env:
  XLA_FLAGS: --xla_force_host_platform_device_count=8

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: test_nt_utils
        run: |
          pytest -k test_nt_utils
      - name: test_data
        run: |
          pytest -k test_data
      - name: test_losses
        run: |
          pytest -k test_losses
      - name: test_models
        run: |
          pytest -k test_models
      - name: test_game
        run: |
          pytest -k test_game
      - name: test_metrics
        run: |
          pytest -k test_metrics
      - name: test_train
        run: |
          pytest -k test_train
      - name: test_main
        run: |
          pytest -k test_main
